package org.parceler;

import android.os.Parcelable;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import org.parceler.NonParcelRepository;

/* compiled from: Parcels.java */
/* renamed from: org.parceler.d */
/* loaded from: classes3.dex */
public final class C11140d {

    /* renamed from: a */
    private static final b f41996a;

    /* compiled from: Parcels.java */
    /* renamed from: org.parceler.d$b */
    private static final class b {

        /* renamed from: a */
        private ConcurrentMap<Class, c> f41997a;

        private b() {
            this.f41997a = new ConcurrentHashMap();
        }

        /* renamed from: a */
        private static String m39876a(Class cls) {
            return cls.getName() + "$$Parcelable";
        }

        /* renamed from: b */
        public c m39877b(Class cls, ClassLoader classLoader) {
            try {
                return new d(cls, classLoader.loadClass(m39876a(cls)));
            } catch (ClassNotFoundException unused) {
                return null;
            }
        }

        /* renamed from: c */
        public c m39878c(Class cls) {
            c cVar = this.f41997a.get(cls);
            if (cVar != null) {
                return cVar;
            }
            c m39877b = m39877b(cls, cls.getClassLoader());
            if (Parcelable.class.isAssignableFrom(cls)) {
                m39877b = new NonParcelRepository.C11130t();
            }
            if (m39877b != null) {
                c putIfAbsent = this.f41997a.putIfAbsent(cls, m39877b);
                return putIfAbsent == null ? m39877b : putIfAbsent;
            }
            throw new ParcelerRuntimeException("Unable to find generated Parcelable class for " + cls.getName() + ", verify that your class is configured properly and that the Parcelable class " + m39876a(cls) + " is generated by Parceler.");
        }

        /* renamed from: d */
        public void m39879d(InterfaceC11141e<c> interfaceC11141e) {
            this.f41997a.putAll(interfaceC11141e.get());
        }
    }

    /* compiled from: Parcels.java */
    /* renamed from: org.parceler.d$c */
    public interface c<T> {
        /* renamed from: a */
        Parcelable mo39835a(T t);
    }

    /* compiled from: Parcels.java */
    /* renamed from: org.parceler.d$d */
    private static final class d<T> implements c<T> {

        /* renamed from: a */
        private final Constructor<? extends Parcelable> f41998a;

        /* JADX WARN: Multi-variable type inference failed */
        public d(Class<T> cls, Class<? extends Parcelable> cls2) {
            try {
                this.f41998a = cls2.getConstructor(cls);
            } catch (NoSuchMethodException e2) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e2);
            }
        }

        @Override // org.parceler.C11140d.c
        /* renamed from: a */
        public Parcelable mo39835a(T t) {
            try {
                return this.f41998a.newInstance(t);
            } catch (IllegalAccessException e2) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e2);
            } catch (InstantiationException e3) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e3);
            } catch (InvocationTargetException e4) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e4);
            }
        }
    }

    static {
        b bVar = new b();
        f41996a = bVar;
        bVar.m39879d(NonParcelRepository.m39754a());
    }

    /* renamed from: a */
    public static <T> T m39873a(Parcelable parcelable) {
        if (parcelable == null) {
            return null;
        }
        return (T) ((InterfaceC11139c) parcelable).getParcel();
    }

    /* renamed from: b */
    public static <T> Parcelable m39874b(Class<? extends T> cls, T t) {
        if (t == null) {
            return null;
        }
        return f41996a.m39878c(cls).mo39835a(t);
    }

    /* renamed from: c */
    public static <T> Parcelable m39875c(T t) {
        if (t == null) {
            return null;
        }
        return m39874b(t.getClass(), t);
    }
}
